name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.0

      - name: Install and Build
        # The symlink can't be resolved by the Deploy action, remove the
        # symlink and copy the packages directory.
        run: |
          dart pub get
          dart pub run build_runner build --release --output build/
          rm build/web/packages
          mv build/packages build/web/packages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build/web
